env: "dev"
token_ttl: 4h

mongo_config:
  db_name: "GRPCMicroservicesCluster"
  conn_string: "mongodb+srv://%s:%s@grpcmicroservicescluste.6q1e9je.mongodb.net/?retryWrites=true&w=majority"
  collections:
    user: "user"
    sequence: "sequence"

clients_config:
  family:
    address: "droplet.senkevichdev.work:33033"
    timeout: 5s
    retries_count: 5

grpc:
  port: 44044
  timeout: 5s